language: python
python:
  - 3.3
  - 3.4

install:
  - pip install --upgrade setuptools
  - pip install coveralls --use-mirrors
  - pip install aiohttp
  - pip install aioredis
  - pip install pycrypto
  - python setup.py develop

script:
  coverage run --source=aiohttp setup.py test
after_success:
  coveralls

env:
  matrix:
    - PYTHONASYNCIODEBUG=1
    - PYTHONASYNCIODEBUG=0
